import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { QueryResultProvider } from "@/components/context/QueryResultContext";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html>
            <QueryResultProvider>
                <body className="flex flex-col min-h-screen bg-zinc-50">
                    <Header />
                    <div className="flex-grow max-w-[1200px] w-full mx-auto my-5 gap-5 overflow-x-auto">
                        {children}
                    </div>
                    <Footer />
                </body>
            </QueryResultProvider>
        </html>
    );
}
